name: fastpork
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy<=1.21
  - numba>=0.55.0
  - pigz
  - rich
  - scipy
  - h5py
  - pytest
  - pyyaml
  - jinja2
  - pip
  - pip:
    - hiyapyco
